apiVersion: v1
data:
  pantheon-cron.yml: |
    pantheon_cron:
      debug: {{ .Values.pantheon_cron.config.debug | quote }}
      stopOnFailure: {{ .Values.pantheon_cron.config.stopOnFailure | quote }}
      {{- with .Values.pantheon_cron.config.sites }}
      sites:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pantheon_cron.config.tasks }}
      tasks:
        {{- toYaml . | nindent 8 }}
      {{- end }}

kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: {{ template "pantheon-cron.fullname" . }}-config

